### ISSUE TITLE
KeyError when enriching from lexicon

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/PolyglotDB#112]
When I try to enrich the lexicon (via the SPADE repo), PolyglotDB throws the following error:

```
Traceback (most recent call last):
  File "sibilant.py", line 40, in <module>
    common.lexicon_enrichment(config, corpus_conf['unisyn_spade_directory'], corpus_conf['dialect_code'])
  File "/home/linguistics/jtanner/SPADE/Common/common.py", line 246, in lexicon_enrichment
    enrich_lexicon_from_csv(g, path)
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/io/enrichment/lexical.py", line 23, in enrich_lexicon_from_csv
    corpus_context.enrich_lexicon(data, type_data, case_sensitive=case_sensitive)
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/corpus/lexical.py", line 32, in enrich_lexicon
    self.encode_hierarchy()
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/corpus/structured.py", line 163, in encode_hierarchy
    sup = self.hierarchy[at]
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/structure.py", line 414, in __getitem__
    return self._data[key]
KeyError: None
```
This only happens for a subset of corpora (Buckeye, Raleigh), but is fine on other corpora (ICE-Can, SOTC) when using the same lexicon CSV.

**Comment by msonderegger** [comment]
do Buckeye and Raleigh have a unisyn dialect code set?  which lexicon csv are you using?

**Comment by james-tanner** [comment]
Buckeye has dialect_code set to 'gam'; Raleigh is set of 'sca'. The lexicon CSV is the one containing just 'word' and 'stresspattern' columns (iscan_lexicon.csv).

**Comment by james-tanner** [comment]
Having thought about this, I feel this might be being caused by the fact that the corpus was reset (and thus no longer has stored information about the hierarchy). If this is the case, it would be fixed when the corpus can be fully reset, and so may be fixed when [https://github.com/MontrealCorpusTools/SPADE/issues/10](url) is resolved.

**Comment by james-tanner** [comment]
Was able to make this work without error on Raleigh after resetting corpus, so I think it's that. I'll close this issue, since the root cause is due to the issue raised in the SPADE repo.

**Comment by msonderegger** [comment]
🎉
