### ISSUE TITLE
Analysing formant tracks crashes during saving

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/PolyglotDB#154]
In trying to output formant tracks (with `output_tracks = True`), the script crashes with the following traceback:
```
Traceback (most recent call last):
  File "formant_dynamic.py", line 88, in <module>
    formant_dynamic_acoustic_analysis(config, vowels_to_analyze, vowel_prototypes_path, drop_formant=drop_formant, duration_threshold = 0.05, num_iterations = 20)
  File "formant_dynamic.py", line 39, in formant_dynamic_acoustic_analysis
    output_tracks = True)
  File "/data/iscan-spade-server/src/polyglotdb/polyglotdb/acoustics/formants/refined.py", line 283, in analyze_formant_points_refinement
    extract_and_save_formant_tracks(corpus_context, best_data, num_formants=True, multiprocessing=multiprocessing, stop_check=stop_check)
  File "/data/iscan-spade-server/src/polyglotdb/polyglotdb/acoustics/formants/helper.py", line 294, in extract_and_save_formant_tracks
    for k, v in output.items():
UnboundLocalError: local variable 'output' referenced before assignment
```

This error doesn't occur for the static points (i.e., not using `output_tracks = True`).

**Comment by MichaelGoodale** [comment]
This is just a simple typo and easy to fix, but it means that whatever segments were passed to the function, ended up being empty.
